version: "3.9"
services:
  fotor:
    build: src
    restart: always
    volumes:
      - ./app/src:/fotor
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"      